##
# Ansible playbook for setting up Oracle JAVA.
#

---
- hosts: all

  tasks:

  - name: general | update apt
    apt: update_cache=yes upgrade=full
    tags: [apt]

  - name: java | install repo
    apt_repository: repo=ppa:webupd8team/java update-cache=yes 
    tags: [java]

  - name: java | accept license
    shell: echo debconf shared/accepted-oracle-license-v1-1 select true | debconf-set-selections
    tags: [java]

  - name: java | install java 8
    apt: pkg=oracle-java8-installer
    tags: [java]